// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohfwpvptkokcdomiqucx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9oZndwdnB0a29rY2RvbWlxdWN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNTgzNTAsImV4cCI6MjA3MzYzNDM1MH0.503-rrxjIGL8bI6_DFJrzs8iGxGa7AGR0iH2WK6zEDI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});